// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TBlacklist
{
    public int Id { get; set; }

    public string BlockedUserId { get; set; }

    public string Reason { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public bool IsActive { get; set; }
}