// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TBlock
{
    public int FBlockSid { get; set; }

    public string FMemberId { get; set; }

    public string FBlockUserId { get; set; }

    public string FBlockType { get; set; }
}