// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TBroker
{
    public string FBrokerId { get; set; }

    public string FBrokerName { get; set; }
}