// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TComment
{
    public int FCommentId { get; set; }

    public int? FPostId { get; set; }

    public string FMemberId { get; set; }

    public string FContent { get; set; }

    public DateTime? FCratedAt { get; set; }

    public DateTime? FUpdateAt { get; set; }
}