// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TCustomerPreference
{
    public int FPreferId { get; set; }

    public string FMemberId { get; set; }

    public int FStockId { get; set; }
}