// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TCustomerInvestAccount
{
    public int FInvestAccountId { get; set; }

    public string FMemberId { get; set; }

    public string FBrokerId { get; set; }

    public string FInvestAccount { get; set; }

    public string FInvestPass { get; set; }
}