// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TDistrict
{
    public int FDistrictId { get; set; }

    public string FDistrict { get; set; }
}