// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TFollower
{
    public int FFollowerSid { get; set; }

    public string FFollowerMemberId { get; set; }

    public string FFollowingMemberId { get; set; }
}