// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class THashtag
{
    public int FHashTagSid { get; set; }

    public string FHashTag { get; set; }

    public int? FPostId { get; set; }

    public string FMemberId { get; set; }

    public string FMemberType { get; set; }
}