// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class THelpSkill
{
    public int FHelpSkillId { get; set; }

    public string FHelpSkill { get; set; }
}