// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class THelpClass
{
    public int FHelpClassId { get; set; }

    public string FHelpClass { get; set; }
}