// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class THelpMessageRecord
{
    public int FMessageRecord { get; set; }

    public int? FHelpId { get; set; }

    public string FContent { get; set; }

    public DateTime? FSendDate { get; set; }

    public int? FPublicOrNot { get; set; }
}