// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TInvestRecord
{
    public int FRepoId { get; set; }

    public string FMemberId { get; set; }

    public DateTime FStartDate { get; set; }

    public DateTime FEndDate { get; set; }

    public int FStockId { get; set; }

    public DateTime? FSoldTime { get; set; }

    public decimal FCost { get; set; }

    public decimal FDealPrice { get; set; }

    public int FStockQty { get; set; }

    public double FProSum { get; set; }

    public double FProTsum { get; set; }
}