// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TLike
{
    public int FLikesSid { get; set; }

    public string FUserId { get; set; }

    public string FPostId { get; set; }

    public string FTimestamp { get; set; }
}