// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TLoginRecord
{
    public int FLogId { get; set; }

    public string FMemberId { get; set; }

    public byte[] FTimestamp { get; set; }

    public string FIp { get; set; }
}