// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TMemberSkill
{
    public string FMemberId { get; set; }

    public int? FHelpSkillId { get; set; }
}