// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TMessage
{
    public int FMessid { get; set; }

    public string FSid { get; set; }

    public string FRid { get; set; }

    public string FMessContent { get; set; }

    public DateTime? FTimestamp { get; set; }

    public string FImagePath { get; set; }

    public string FImageName { get; set; }

    public string FMessType { get; set; }

    public bool FIsRead { get; set; }

    public DateTime FCreateTime { get; set; }

    public DateTime? FUpdateTime { get; set; }
}