// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TMgerScActivity
{
    public int FActivityId { get; set; }

    public string FMemberId { get; set; }

    public string FActivityType { get; set; }

    public byte[] FOccurreAt { get; set; }
}