// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TMgrScFile
{
    public int FFileId { get; set; }

    public string FMemberId { get; set; }

    public string FFileName { get; set; }

    public string FFilePath { get; set; }

    public string FFileType { get; set; }

    public byte[] FUploadateAt { get; set; }
}