// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TOrderDetail
{
    public int FOrderDetailId { get; set; }

    public int FOrderId { get; set; }

    public int? FProductId { get; set; }

    public int? FAmount { get; set; }

    public int? FHelpPoint { get; set; }
}