// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TPointList
{
    public int FPointListId { get; set; }

    public string FMemberId { get; set; }

    public int? FMatchId { get; set; }

    public int? FOrderId { get; set; }

    public int? FSourse { get; set; }

    public DateTime? FRecordTime { get; set; }
}