// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TPost
{
    public int FPostId { get; set; }

    public string FMemberId { get; set; }

    public string FUserName { get; set; }

    public string FPostContent { get; set; }

    public int? FLikes { get; set; }

    public DateTime? FCreatedTime { get; set; }

    public string FMemberType { get; set; }

    public int? FParentCommentId { get; set; }

    public byte[] FFinStatement { get; set; }
}