// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TProductCategory
{
    public int FProductCategoryId { get; set; }

    public string FProductCategoryName { get; set; }

    public string FDescription { get; set; }
}