// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TRefreshToken
{
    public string FId { get; set; }

    public string FToken { get; set; }

    public DateTime FExpiryDate { get; set; }

    public string FUserId { get; set; }

    public bool FIsRevoked { get; set; }

    public DateTime FCreatedAt { get; set; }

    public string FCreatedByIp { get; set; }

    public DateTime? FRevokedAt { get; set; }

    public string FRevokedByIp { get; set; }

    public string FReplacedByToken { get; set; }
}