// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TSponsorCategory
{
    public int FSponsorCategoryId { get; set; }

    public string FSponsorCategoryrName { get; set; }

    public string FDescription { get; set; }
}