// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TStockInStock
{
    public int FInStockId { get; set; }

    public string FMemberId { get; set; }

    public string FBrokerId { get; set; }

    public string FStockId { get; set; }

    public string FStockName { get; set; }

    public string FTranType { get; set; }

    public int? FLeftStock { get; set; }

    public int? FStockAdj { get; set; }

    public int? FStockNow { get; set; }

    public int? FStockTran { get; set; }

    public decimal? FStockPriceN { get; set; }

    public decimal? FStockPriceT { get; set; }

    public decimal? FStockPriceTs { get; set; }

    public decimal? FStockCost { get; set; }

    public decimal? FEstPro { get; set; }

    public double? FEstProP { get; set; }

    public decimal? FBalancePrice { get; set; }
}