// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjWankibackend.Models.Database;

public partial class TStock
{
    public string FStockId { get; set; }

    public string FStockName { get; set; }

    public decimal? FStockPriceN { get; set; }
}